
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking
    username: moldori
    password: moldori123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: 'create-drop'
